USE codeup_test_db;

DROP IF EXISTS albums;

CREATE TABLE albums(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist VARCHAR(50) NOT NULL,
  name VARCHAR(50) DEFAULT NULL,
  release_date YEAR(4),
  sales NUMERIC DEFAULT NULL,
  genre VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY ('id'),
)

